name: Crowdin Action

on:
    workflow_dispatch
  # push:
  #   branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.4
      with:
        upload_translations: true
        download_translations: true
        crowdin_branch_name: l10n_branch
        localization_branch_name: l10n_crowdin_action

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
  # with:
  #   # upload options
  #   upload_sources: true
  #   upload_translations: true

  #   # download options
  #   download_translations: true
  #   language: 'uk'
  #   push_translations: true

  #   # This is the name of the git branch that Crowdin will create when opening a pull request. 
  #   # This branch does NOT need to be manually created. It will be created automatically by the action.
  #   localization_branch_name: l10n_crowdin_action
  #   create_pull_request: true

  #   # global options
    
  #   # This is the name of the top-level directory that Crowdin will use for files.
  #   # Note that this is not a "branch" in the git sense, but more like a top-level directory in your Crowdin project.
  #   # This branch does NOT need to be manually created. It will be created automatically by the action.
  #   crowdin_branch_name: l10n_branch
  #   #identity: '/path/to/your/credentials/file'
  #   config: 'crowdin.yml'
  #   dryrun_action: true

  #   # config options
    
  #   # This is a numeric id, not to be confused with Crowdin API v1 "project identifier" string
  #   # See "API v2" on https://crowdin.com/project/<your-project>/settings#api
  #   #project_id: 

  #   # A personal access token, not to be confused with Crowdin API v1 "API key"
  #   # See https://crowdin.com/settings#api-key to generate a token
  #   #token: $
  #   #source: '/path/to/your/file'
  #   #translation: 'file/export/pattern'
  #   #base_url: 'https://crowdin.com'
  #   #base_path: '/project-base-path'
