name: Check commits on pull
on: [pull]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check commits
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Lint
      uses: pmarnik/git-lint-action@v1
