name: Check commits
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Validate commits
      id: hello
      uses: pmarnik/hello-world-docker-action@v1
